language: php

php:
  - 7.2

before_script:
  - curl --version
  #Composer
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml --colors
